paths:
  /api/Anime/AddAnime/{animeId}:
    get:
      summary: Your endpoint summary
      parameters:
        - in: query  # or path, header, or formData, depending on where your parameter is located
          name: objectId
          description: MongoDB ObjectId parameter
          required: true
          schema:
            type: string
            example: "607ca0699c481c41f0ff59df"  # Example ObjectId value as a hexadecimal string
      responses:
        '200':
          description: Successful response