/**
 * Proiect disertație
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AppUserAnimeItem } from './appUserAnimeItem';
import { AppUserBookItem } from './appUserBookItem';
import { AppUserGameItem } from './appUserGameItem';
import { AppUserMangaItem } from './appUserMangaItem';
import { AppUserMovieItem } from './appUserMovieItem';
import { AppUserRole } from './appUserRole';
import { AppUserTvShowItem } from './appUserTvShowItem';
import { FriendRequest } from './friendRequest';
import { Friendships } from './friendships';
import { Message } from './message';
import { Photo } from './photo';
import { Review } from './review';

export interface AppUser { 
    id?: string;
    userName?: string;
    normalizedUserName?: string;
    email?: string;
    normalizedEmail?: string;
    emailConfirmed?: boolean;
    passwordHash?: string;
    securityStamp?: string;
    concurrencyStamp?: string;
    phoneNumber?: string;
    phoneNumberConfirmed?: boolean;
    twoFactorEnabled?: boolean;
    lockoutEnd?: Date;
    lockoutEnabled?: boolean;
    accessFailedCount?: number;
    dateOfBirth?: Date;
    knownAs?: string;
    created?: Date;
    lastActive?: Date;
    gender?: string;
    introduction?: string;
    interests?: string;
    city?: string;
    country?: string;
    photos?: Photo;
    friendRequests?: Array<FriendRequest>;
    friends?: Array<Friendships>;
    messagesSent?: Array<Message>;
    messagesReceived?: Array<Message>;
    userRoles?: Array<AppUserRole>;
    appUserMovie?: Array<AppUserMovieItem>;
    appUserTvShow?: Array<AppUserTvShowItem>;
    appUserAnime?: Array<AppUserAnimeItem>;
    appUserManga?: Array<AppUserMangaItem>;
    appUserGame?: Array<AppUserGameItem>;
    appUserBook?: Array<AppUserBookItem>;
    isSubscribedToNewsletter?: boolean;
    hasDarkMode?: boolean;
    reviews?: Array<Review>;
}