/**
 * Proiect disertație
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */import { ObjectId } from './objectId';


export interface Book { 
    id?: ObjectId;
    bookID?: number;
    title?: string;
    authors?: string;
    averageRating?: number;
    isbn?: string;
    isbn13?: number;
    languageCode?: string;
    numPages?: number;
    ratingsCount?: number;
    textReviewsCount?: number;
    publicationDate?: string;
    publisher?: string;
    coverUrl?: string;
    reviewsIds?: Array<string>;
}