/**
 * Proiect disertație
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Cast { 
    adult?: boolean;
    gender?: number;
    id?: number;
    knownForDepartment?: string;
    name?: string;
    originalName?: string;
    popularity?: number;
    profilePath?: string;
    castId?: number;
    character?: string;
    creditId?: string;
    order?: number;
}