/**
 * Proiect_licenta
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ThemeManga } from './themeManga';
import { AppUserMangaItem } from './appUserMangaItem';
import { SerializationManga } from './serializationManga';
import { DemographicManga } from './demographicManga';
import { GenreManga } from './genreManga';
import { AuthorManga } from './authorManga';
import { ImagesManga } from './imagesManga';
import { PublishedManga } from './publishedManga';


export interface DatumManga { 
    mal_id?: number;
    url?: string | null;
    images?: ImagesManga;
    title?: string | null;
    title_english?: string | null;
    title_japanese?: string | null;
    type?: string | null;
    chapters?: number | null;
    volumes?: number | null;
    status?: string | null;
    publishing?: boolean;
    published?: PublishedManga;
    score?: number | null;
    scored?: number;
    scored_by?: number;
    rank?: number | null;
    popularity?: number | null;
    members?: number;
    favorites?: number;
    synopsis?: string | null;
    background?: string | null;
    authors?: Array<AuthorManga> | null;
    serializations?: Array<SerializationManga> | null;
    genres?: Array<GenreManga> | null;
    themes?: Array<ThemeManga> | null;
    demographics?: Array<DemographicManga> | null;
    appUserManga?: Array<AppUserMangaItem> | null;
}

