/**
 * Proiect disertație
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Aired } from './aired';
import { Broadcast } from './broadcast';
import { Demographic } from './demographic';
import { Genre } from './genre';
import { Images } from './images';
import { Licensor } from './licensor';
import { ObjectId } from './objectId';
import { Producer } from './producer';
import { Studio } from './studio';
import { Theme } from './theme';
import { Trailer } from './trailer';

export interface Datum { 
    id?: ObjectId;
    mal_id?: number;
    url?: string;
    images?: Images;
    trailer?: Trailer;
    title?: string;
    title_english?: string;
    title_japanese?: string;
    type?: string;
    source?: string;
    episodes?: number;
    status?: string;
    airing?: boolean;
    aired?: Aired;
    duration?: string;
    rating?: string;
    score?: number;
    scored_by?: number;
    rank?: number;
    popularity?: number;
    members?: number;
    favorites?: number;
    synopsis?: string;
    background?: string;
    season?: string;
    year?: number;
    broadcast?: Broadcast;
    producers?: Array<Producer>;
    licensors?: Array<Licensor>;
    studios?: Array<Studio>;
    genres?: Array<Genre>;
    themes?: Array<Theme>;
    demographics?: Array<Demographic>;
    reviews_ids?: Array<string>;
}