/**
 * Proiect disertație
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AddedByStatusGame } from './addedByStatusGame';
import { DeveloperGame } from './developerGame';
import { EsrbRatingGame } from './esrbRatingGame';
import { GenreGame } from './genreGame';
import { ObjectId } from './objectId';
import { PlatformsGame } from './platformsGame';
import { PublisherGame } from './publisherGame';
import { RatingGame } from './ratingGame';
import { StoresGame } from './storesGame';
import { TagGame } from './tagGame';

export interface Game { 
    id?: ObjectId;
    game_id?: number;
    slug?: string;
    name?: string;
    description?: string;
    metacritic?: number;
    released?: string;
    tba?: boolean;
    updated?: Date;
    background_image?: string;
    background_image_additional?: string;
    website?: string;
    rating?: number;
    rating_top?: number;
    ratings?: Array<RatingGame>;
    added?: number;
    added_by_status?: AddedByStatusGame;
    movies_count?: number;
    creators_count?: number;
    achievements_count?: number;
    parent_achievements_count?: number;
    twitch_count?: number;
    youtube_count?: number;
    reviews_text_count?: number;
    ratings_count?: number;
    suggestions_count?: number;
    metacritic_url?: string;
    game_series_count?: number;
    reviews_count?: number;
    platforms?: Array<PlatformsGame>;
    stores?: Array<StoresGame>;
    developers?: Array<DeveloperGame>;
    genres?: Array<GenreGame>;
    tags?: Array<TagGame>;
    publishers?: Array<PublisherGame>;
    esrb_rating?: EsrbRatingGame;
    description_raw?: string;
    reviews_ids?: Array<string>;
}