/**
 * Proiect_disertatie
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface MemberDto { 
    id?: string;
    userName?: string;
    photoUrl?: string;
    age?: number;
    knownAs?: string;
    created?: Date;
    lastActive?: Date;
    gender?: string;
    introduction?: string;
    interests?: string;
    city?: string;
    country?: string;
    isSubscribedToNewsletter?: boolean;
}