/**
 * Proiect disertație
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface MemberDto { 
    id?: string;
    user_name?: string;
    photo_url?: string;
    age?: number;
    known_as?: string;
    created?: Date;
    last_active?: Date;
    gender?: string;
    introduction?: string;
    interests?: string;
    city?: string;
    country?: string;
    is_subscribed_to_newsletter?: boolean;
}