/**
 * Proiect disertație
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */import { AppUser } from './appUser';


export interface Message { 
    id?: number;
    senderId?: number;
    senderUsername?: string;
    sender?: AppUser;
    recipientId?: number;
    recipientUsername?: string;
    recipient?: AppUser;
    content?: string;
    dateRead?: Date;
    messageSent?: Date;
    senderDeleted?: boolean;
    recipientDeleted?: boolean;
}