/**
 * Proiect_disertatie
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface MessageDto { 
    id?: number;
    senderId?: number;
    senderUsername?: string;
    senderPhotoUrl?: string;
    recipientId?: number;
    recipientUsername?: string;
    recipientPhotoUrl?: string;
    content?: string;
    dateRead?: Date;
    messageSent?: Date;
}