/**
 * Proiect disertație
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BelongsToCollection } from './belongsToCollection';
import { Credits } from './credits';
import { MovieGenre } from './movieGenre';
import { MovieImages } from './movieImages';
import { ObjectId } from './objectId';
import { ProductionCompany } from './productionCompany';
import { ProductionCountry } from './productionCountry';
import { Similar } from './similar';
import { SpokenLanguage } from './spokenLanguage';
import { Videos } from './videos';

export interface Movie { 
    movie_id?: ObjectId;
    backdrop_path?: string;
    belongs_to_collection?: BelongsToCollection;
    budget?: number;
    genres?: Array<MovieGenre>;
    homepage?: string;
    id?: number;
    imdb_id?: string;
    origin_country?: Array<string>;
    original_language?: string;
    original_title?: string;
    overview?: string;
    popularity?: number;
    poster_path?: string;
    production_companies?: Array<ProductionCompany>;
    production_countries?: Array<ProductionCountry>;
    release_date?: string;
    revenue?: number;
    runtime?: number;
    spoken_languages?: Array<SpokenLanguage>;
    status?: string;
    tagline?: string;
    title?: string;
    vote_average?: number;
    vote_count?: number;
    videos?: Videos;
    similar?: Similar;
    images?: MovieImages;
    credits?: Credits;
    reviews_ids?: Array<string>;
}