/**
 * Proiect_disertatie
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface MoviesTrailer { 
    imDbId?: string;
    title?: string;
    fullTitle?: string;
    type?: string;
    year?: string;
    videoId?: string;
    videoTitle?: string;
    videoDescription?: string;
    thumbnailUrl?: string;
    link?: string;
    linkEmbed?: string;
    errorMessage?: string;
}