/**
 * Proiect_licenta
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CompanyList } from './companyList';
import { DirectorList } from './directorList';
import { ActorList } from './actorList';
import { BoxOffice } from './boxOffice';
import { Similar } from './similar';
import { Wikipedia } from './wikipedia';
import { MoviesTrailer } from './moviesTrailer';
import { LanguageList } from './languageList';
import { Ratings } from './ratings';
import { WriterList } from './writerList';
import { AppUserMovieItem } from './appUserMovieItem';
import { StarList } from './starList';
import { CountryList } from './countryList';
import { GenreList } from './genreList';
import { MoviesImages } from './moviesImages';


export interface Movie { 
    id?: string | null;
    title?: string | null;
    originalTitle?: string | null;
    fullTitle?: string | null;
    type?: string | null;
    year?: string | null;
    image?: string | null;
    releaseDate?: string | null;
    runtimeMins?: string | null;
    runtimeStr?: string | null;
    plot?: string | null;
    plotLocal?: string | null;
    plotLocalIsRtl?: boolean;
    awards?: string | null;
    directors?: string | null;
    directorList?: Array<DirectorList> | null;
    writers?: string | null;
    writerList?: Array<WriterList> | null;
    stars?: string | null;
    starList?: Array<StarList> | null;
    actorList?: Array<ActorList> | null;
    genres?: string | null;
    genreList?: Array<GenreList> | null;
    companies?: string | null;
    companyList?: Array<CompanyList> | null;
    countries?: string | null;
    countryList?: Array<CountryList> | null;
    languages?: string | null;
    languageList?: Array<LanguageList> | null;
    contentRating?: string | null;
    imDbRating?: string | null;
    imDbRatingVotes?: string | null;
    metacriticRating?: string | null;
    ratings?: Ratings;
    wikipedia?: Wikipedia;
    images?: MoviesImages;
    trailer?: MoviesTrailer;
    boxOffice?: BoxOffice;
    tagline?: string | null;
    keywords?: string | null;
    similars?: Array<Similar> | null;
    appUserMovie?: Array<AppUserMovieItem> | null;
}

