/**
 * Proiect_licenta
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PlatformGame { 
    platformGameId?: string;
    name?: string | null;
    slug?: string | null;
    id?: number;
    image?: string | null;
    year_end?: number | null;
    year_start?: number | null;
    games_count?: number;
    image_background?: string | null;
}

