/**
 * Proiect_disertatie
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */import { FromManga } from './fromManga';
import { ToManga } from './toManga';


export interface PropManga { 
    from?: FromManga;
    to?: ToManga;
}