/**
 * Proiect_licenta
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Ratings { 
    id?: string;
    imDbId?: string | null;
    title?: string | null;
    fullTitle?: string | null;
    type?: string | null;
    year?: string | null;
    imDb?: string | null;
    metacritic?: string | null;
    theMovieDb?: string | null;
    rottenTomatoes?: string | null;
    filmAffinity?: string | null;
    errorMessage?: string | null;
}

