/**
 * Proiect_licenta
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface RegisterDto { 
    username: string;
    email: string;
    knownAs: string;
    gender: string;
    dateOfBirth: Date;
    city: string;
    country: string;
    password: string;
}