/**
 * Proiect disertație
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AppUser } from './appUser';

export interface Review { 
    reviewId?: string;
    user_id?: string;
    username?: string;
    user_photo?: string;
    user?: AppUser;
    item_id?: string;
    short_description?: string;
    main_description?: string;
    stars?: number;
    reviewDate?: Date;
    likes?: number;
    dislikes?: number;
}