/**
 * Proiect_licenta
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Images } from './images';


export interface Trailer { 
    id?: string;
    youtube_id?: string | null;
    url?: string | null;
    embed_url?: string | null;
    images?: Images;
}

