/**
 * Proiect_licenta
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvShowPlotShort } from './tvShowPlotShort';
import { TvShowPlotFull } from './tvShowPlotFull';


export interface TvShowWikipedia { 
    tvShowWikipediaId?: string;
    imDbId?: string | null;
    title?: string | null;
    fullTitle?: string | null;
    type?: string | null;
    year?: string | null;
    language?: string | null;
    titleInLanguage?: string | null;
    url?: string | null;
    plotShort?: TvShowPlotShort;
    plotFull?: TvShowPlotFull;
    errorMessage?: string | null;
}

