/**
 * Proiect disertație
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ObjectId } from './objectId';
import { TvShowCreatedBy } from './tvShowCreatedBy';
import { TvShowCredits } from './tvShowCredits';
import { TvShowGenre } from './tvShowGenre';
import { TvShowImages } from './tvShowImages';
import { TvShowLastEpisodeToAir } from './tvShowLastEpisodeToAir';
import { TvShowNetwork } from './tvShowNetwork';
import { TvShowProductionCompany } from './tvShowProductionCompany';
import { TvShowProductionCountry } from './tvShowProductionCountry';
import { TvShowSeason } from './tvShowSeason';
import { TvShowSimilar } from './tvShowSimilar';
import { TvShowSpokenLanguage } from './tvShowSpokenLanguage';
import { TvShowVideos } from './tvShowVideos';

export interface TvShow { 
    id?: ObjectId;
    adult?: boolean;
    backdropPath?: string;
    createdBy?: Array<TvShowCreatedBy>;
    episodeRunTime?: Array<number>;
    firstAirDate?: string;
    genres?: Array<TvShowGenre>;
    homepage?: string;
    tvShowId?: number;
    inProduction?: boolean;
    languages?: Array<string>;
    lastAirDate?: string;
    lastEpisodeToAir?: TvShowLastEpisodeToAir;
    name?: string;
    networks?: Array<TvShowNetwork>;
    numberOfEpisodes?: number;
    numberOfSeasons?: number;
    originCountry?: Array<string>;
    originalLanguage?: string;
    originalName?: string;
    overview?: string;
    popularity?: number;
    posterPath?: string;
    productionCompanies?: Array<TvShowProductionCompany>;
    productionCountries?: Array<TvShowProductionCountry>;
    seasons?: Array<TvShowSeason>;
    spokenLanguages?: Array<TvShowSpokenLanguage>;
    status?: string;
    tagline?: string;
    type?: string;
    voteAverage?: number;
    voteCount?: number;
    videos?: TvShowVideos;
    similar?: TvShowSimilar;
    images?: TvShowImages;
    credits?: TvShowCredits;
    reviewsIds?: Array<string>;
}