/**
 * Proiect disertație
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface TvShowLastEpisodeToAir { 
    id?: number;
    overview?: string;
    name?: string;
    voteAverage?: number;
    voteCount?: number;
    airDate?: string;
    episodeNumber?: number;
    episodeType?: string;
    productionCode?: string;
    runtime?: number;
    seasonNumber?: number;
    showId?: number;
    stillPath?: string;
}