/**
 * Proiect disertație
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ObjectId } from './objectId';
import { TvShowCreatedBy } from './tvShowCreatedBy';
import { TvShowCredits } from './tvShowCredits';
import { TvShowGenre } from './tvShowGenre';
import { TvShowImages } from './tvShowImages';
import { TvShowLastEpisodeToAir } from './tvShowLastEpisodeToAir';
import { TvShowNetwork } from './tvShowNetwork';
import { TvShowProductionCompany } from './tvShowProductionCompany';
import { TvShowProductionCountry } from './tvShowProductionCountry';
import { TvShowSeason } from './tvShowSeason';
import { TvShowSimilar } from './tvShowSimilar';
import { TvShowSpokenLanguage } from './tvShowSpokenLanguage';
import { TvShowVideos } from './tvShowVideos';

export interface TvShow { 
    id?: ObjectId;
    adult?: boolean;
    backdrop_path?: string;
    created_by?: Array<TvShowCreatedBy>;
    episode_run_time?: Array<number>;
    first_air_date?: string;
    genres?: Array<TvShowGenre>;
    homepage?: string;
    movie_id?: number;
    in_production?: boolean;
    languages?: Array<string>;
    last_air_date?: string;
    last_episode_to_air?: TvShowLastEpisodeToAir;
    name?: string;
    networks?: Array<TvShowNetwork>;
    number_of_episodes?: number;
    number_of_seasons?: number;
    origin_country?: Array<string>;
    original_language?: string;
    original_name?: string;
    overview?: string;
    popularity?: number;
    poster_path?: string;
    production_companies?: Array<TvShowProductionCompany>;
    production_countries?: Array<TvShowProductionCountry>;
    seasons?: Array<TvShowSeason>;
    spoken_languages?: Array<TvShowSpokenLanguage>;
    status?: string;
    tagline?: string;
    type?: string;
    vote_average?: number;
    vote_count?: number;
    videos?: TvShowVideos;
    similar?: TvShowSimilar;
    images?: TvShowImages;
    credits?: TvShowCredits;
    reviews_ids?: Array<string>;
}