/**
 * Proiect_licenta
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ObjectId } from './objectId';
import { TvSeriesInfo } from './tvSeriesInfo';
import { TvShowActorList } from './tvShowActorList';
import { TvShowBoxOffice } from './tvShowBoxOffice';
import { TvShowCompanyList } from './tvShowCompanyList';
import { TvShowCountryList } from './tvShowCountryList';
import { TvShowGenreList } from './tvShowGenreList';
import { TvShowImages } from './tvShowImages';
import { TvShowLanguageList } from './tvShowLanguageList';
import { TvShowRatings } from './tvShowRatings';
import { TvShowSimilar } from './tvShowSimilar';
import { TvShowStarList } from './tvShowStarList';
import { TvShowTrailer } from './tvShowTrailer';
import { TvShowWikipedia } from './tvShowWikipedia';

export interface TvShow { 
    id?: ObjectId;
    tvShowId?: string;
    title?: string;
    originalTitle?: string;
    fullTitle?: string;
    type?: string;
    year?: string;
    image?: string;
    releaseDate?: string;
    runtimeMins?: string;
    runtimeStr?: string;
    plot?: string;
    plotLocal?: string;
    plotLocalIsRtl?: boolean;
    awards?: string;
    directors?: string;
    writers?: string;
    stars?: string;
    starList?: Array<TvShowStarList>;
    actorList?: Array<TvShowActorList>;
    genres?: string;
    genreList?: Array<TvShowGenreList>;
    companies?: string;
    companyList?: Array<TvShowCompanyList>;
    countries?: string;
    countryList?: Array<TvShowCountryList>;
    languages?: string;
    languageList?: Array<TvShowLanguageList>;
    contentRating?: string;
    imDbRating?: string;
    imDbRatingVotes?: string;
    metacriticRating?: string;
    ratings?: TvShowRatings;
    wikipedia?: TvShowWikipedia;
    images?: TvShowImages;
    trailer?: TvShowTrailer;
    boxOffice?: TvShowBoxOffice;
    keywords?: string;
    similars?: Array<TvShowSimilar>;
    tvSeriesInfo?: TvSeriesInfo;
}