/**
 * Proiect disertație
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UserDto { 
    username?: string;
    token?: string;
    photo_url?: string;
    known_as?: string;
    gender?: string;
    email?: string;
    is_subscribed?: boolean;
    has_dark_mode?: boolean;
}