/**
 * Proiect_disertatie
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */import { PlotFull } from './plotFull';
import { PlotShort } from './plotShort';


export interface Wikipedia { 
    imDbId?: string;
    title?: string;
    fullTitle?: string;
    type?: string;
    year?: string;
    language?: string;
    titleInLanguage?: string;
    url?: string;
    plotShort?: PlotShort;
    plotFull?: PlotFull;
    errorMessage?: string;
}